/**
 * 手绘位图(字符画):返回钮、主菜单入口图标、敌情图标、套组图标。
 * 每张图 = 等长字符串数组;字符经 LEGEND 映射到 33 色名;'.' 为透明。
 * 尺寸与 artwork/pixel-kit-chrome.json 里的 w/h 一致,由生成器校验。
 */

export const LEGEND = {
  k: "ink",
  d: "deep",
  n: "navy1",
  m: "navy2",
  a: "slate0",
  s: "slate1",
  u: "steel0",
  S: "steel1",
  T: "steel2",
  L: "steel3",
  w: "bone0",
  W: "bone1",
  o: "gold0",
  g: "gold1",
  G: "gold2",
  Y: "gold3",
  q: "red0",
  r: "red1",
  R: "red2",
  X: "red3",
  h: "teal0",
  t: "teal1",
  e: "teal2",
  E: "teal3",
  z: "violet0",
  v: "violet1",
  V: "violet2",
  P: "violet3",
  i: "blue0",
  b: "blue1",
  B: "blue2",
  C: "blue3",
};

export const BITMAPS = {
  /* 返回箭头 11×11:粗箭头,骨白填充 + 墨线,任意底板上都读得出 */
  btn_back: [
    ".....k.....",
    "....kWk....",
    "...kWWk....",
    "..kWWWkkkkk",
    ".kWWWWWWWWk",
    "kWWWWwwwwwk",
    ".kWWwwwwwwk",
    "..kWwwkkkkk",
    "...kwwk....",
    "....kwk....",
    ".....k.....",
  ],

  /* ---- 主菜单入口 16×16(屏上 2× 落格) ---- */
  /* 委托:两端金轴的卷轴,羊皮纸上三行字 */
  entry_quests: [
    "................",
    "..kkkkkkkkkkkk..",
    ".kGYYYYYYYYYYGk.",
    ".kgGGGGGGGGGGgk.",
    "..kwWWWWWWWWwk..",
    "..kwWSSSSSSWwk..",
    "..kwWWWWWWWWwk..",
    "..kwWSSSSSWWwk..",
    "..kwWWWWWWWWwk..",
    "..kwWSSSSSSWwk..",
    "..kwWWWWWWWWwk..",
    ".kGYYYYYYYYYYGk.",
    ".kgGGGGGGGGGGgk.",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ],
  /* 扭蛋:紫顶白底的胶囊蛋,中缝一道 */
  entry_gacha: [
    "................",
    "......kkkk......",
    "....kkPPPPkk....",
    "...kPPVVVVPPk...",
    "..kPVVVVVVVVPk..",
    "..kVVVVVVVVVVk..",
    "..kvVVVVVVVVvk..",
    ".kkkkkkkkkkkkkk.",
    ".kWWWWWWWWWWWWk.",
    "..kwWWWWWWWWwk..",
    "..kwwwwwwwwwwk..",
    "..kwwwwSSwwwwk..",
    "...kwwwSSwwwk...",
    "....kkwwwwkk....",
    "......kkkk......",
    "................",
  ],
  /* 天赋:回响翠五角星,心部略暗 */
  entry_talents: [
    "................",
    ".......kk.......",
    "......kEEk......",
    "......kEEk......",
    ".kk..kEEEEk..kk.",
    "kEEkkEEEEEEkkEEk",
    "kEEEEEEeeEEEEEEk",
    ".kEEEEeeeeEEEEk.",
    "..kEEEeeeeEEEk..",
    "...kEEeeeeEEk...",
    "...kEEEeeEEEk...",
    "..kEEEkkkkEEEk..",
    ".kEEEk....kEEEk.",
    ".kEEk......kEEk.",
    "..kk........kk..",
    "................",
  ],
  /* 通行证:两侧带缺口的金色票券,中央一枚骨白菱星 */
  entry_pass: [
    "................",
    "................",
    ".kkkkkkkkkkkkkk.",
    "kGYYYYYYYYYYYYGk",
    "kGYYYYYYkYYYYYGk",
    "kGYYYYYkWkYYYYGk",
    ".kGYYYkWWWkYYGk.",
    ".kGYYYYkWkYYYGk.",
    ".kGYYYYYkYYYYGk.",
    "kGYYYYYYYYYYYYGk",
    "kGGGGGGGGGGGGGGk",
    "kgggggggggggggGk",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
  ],
  /* 每日:赤色页眉的日历,格点中一枚翠色当日 */
  entry_forge: [
    "................",
    "...kk......kk...",
    "...kSk....kSk...",
    ".kkkkkkkkkkkkkk.",
    "kRRRRRRRRRRRRRRk",
    "krrrrrrrrrrrrrrk",
    "kkkkkkkkkkkkkkkk",
    "kWWWWWWWWWWWWWWk",
    "kWSSWWSSWWSSWWWk",
    "kWWWWWWWWWWWWWWk",
    "kWSSWWEEWWSSWWWk",
    "kWWWWWEEWWWWWWWk",
    "kWSSWWSSWWSSWWWk",
    "kWWWWWWWWWWWWWWk",
    ".kkkkkkkkkkkkkk.",
    "................",
  ],
  /* 升级:钢座上一支向上的金箭 */
  entry_gearup: [
    "................",
    ".......kk.......",
    "......kYYk......",
    ".....kYYYYk.....",
    "....kYYGGYYk....",
    "...kYYGGGGYYk...",
    "..kYYGGGGGGYYk..",
    ".kkkkkGGGGkkkkk.",
    ".....kGGGGk.....",
    ".....kGGGGk.....",
    ".....kgGGgk.....",
    ".....kkkkkk.....",
    ".kkkkkkkkkkkkkk.",
    "kSSSTTTTTTTTSSSk",
    "kuuuSSSSSSSSuuuk",
    ".kkkkkkkkkkkkkk.",
  ],

  /* ---- 敌情 12×12(屏上 1:1,只留大剪影) ---- */
  /* 尸潮:骨白颅骨 */
  intel_horde: [
    "....kkkk....",
    "..kkwwwwkk..",
    ".kwwwwwwwwk.",
    ".kwwwwwwwwk.",
    "kwwkkwwkkwwk",
    "kwwkkwwkkwwk",
    "kwwwwwwwwwwk",
    ".kwwwkkwwwk.",
    ".kkwwwwwwkk.",
    "..kwkwwkwk..",
    "..kkkkkkkk..",
    "............",
  ],
  /* 重甲:钢盾,中央亮脊 */
  intel_armor: [
    "kkkkkkkkkkkk",
    "kSSSTLLTSSSk",
    "kSSSTLLTSSSk",
    "kSSSTLLTSSSk",
    "kuuuSTTSuuuk",
    "kuuuSTTSuuuk",
    ".kuuSTTSuuk.",
    ".kuuSTTSuuk.",
    "..kuuSSuuk..",
    "...kuSSuk...",
    "....kkkk....",
    "............",
  ],
  /* 异变:紫巩膜翠瞳的竖瞳巨眼 */
  intel_mutant: [
    "............",
    "....kkkk....",
    "..kkVVVVkk..",
    ".kVVPPPPVVk.",
    "kVPPkkkkPPVk",
    "kVPkEEEEkPVk",
    "kVPkEkkEkPVk",
    "kVPPkEEkPPVk",
    ".kVVPkkPVVk.",
    "..kkVVVVkk..",
    "....kkkk....",
    "............",
  ],
  /* 精英:三尖金冠,嵌两枚赤宝石 */
  intel_elite: [
    "............",
    "k....kk....k",
    "kk..kYYk..kk",
    "kYk.kYYk.kYk",
    "kYYkkYYkkYYk",
    "kYYYYYYYYYYk",
    "kYGGGGGGGGYk",
    "kYGGRRGGRRYk",
    "kYGGGGGGGGYk",
    "kggggggggggk",
    "kkkkkkkkkkkk",
    "............",
  ],

  /* ---- 套组 18×18(屏上 1:1) ---- */
  /* 荆棘回响:八刺荆环 */
  icon_set_thorn: [
    "......kk..kk......",
    ".....kEk..kEk.....",
    "..kk.kEEkkEEk.kk..",
    ".kEEkkEttttEkkEEk.",
    ".kEEEEttkkttEEEEk.",
    "..kEEtt....ttEEk..",
    ".kkEtt......ttEkk.",
    "kEEEt........tEEEk",
    "kEtt..........ttEk",
    "kEtt..........ttEk",
    "kEEEt........tEEEk",
    ".kkEtt......ttEkk.",
    "..kEEtt....ttEEk..",
    ".kEEEEttkkttEEEEk.",
    ".kEEkkEttttEkkEEk.",
    "..kk.kEEkkEEk.kk..",
    ".....kEk..kEk.....",
    "......kk..kk......",
  ],
  /* 弹幕风暴:三支并排上行的寒冰弹 */
  icon_set_barrage: [
    "..................",
    "....k....k....k...",
    "...kCk..kCk..kCk..",
    "...kCk..kCk..kCk..",
    "..kCBCkkCBCkkCBCk.",
    "..kCBCkkCBCkkCBCk.",
    "..kBBBkkBBBkkBBBk.",
    "..kBBBkkBBBkkBBBk.",
    "..kBBBkkBBBkkBBBk.",
    "..kBBBkkBBBkkBBBk.",
    "..kbBbkkbBbkkbBbk.",
    "..kbBbkkbBbkkbBbk.",
    ".kkbbbkkbbbkkbbbkk",
    ".kwbbbwkwbbbwkwbbw",
    ".kwkkkwkwkkkwkwkkw",
    ".kkk.kkkkk.kkkkk.k",
    "..................",
    "..................",
  ],
  /* 余烬天灾:金心赤焰 */
  icon_set_ember: [
    "........kk........",
    ".......kRk........",
    "......kRRk........",
    "......kRRRk..kk...",
    ".....kRRRRk.kRk...",
    ".....kRRRRRkkRk...",
    "....kRRRRRRRRRk...",
    "....kRRGGRRRRRk...",
    "...kRRGYYGRRRRRk..",
    "...kRGYYYYGRRRRk..",
    "..kRRGYYYYYGRRRk..",
    "..kRGYYYYYYYGRRk..",
    "..kRGYYYYYYYGRRk..",
    "..kRRGYYYYYGRRk...",
    "...kRRGGGGGRRk....",
    "....kRRRRRRRk.....",
    ".....kkkkkkk......",
    "..................",
  ],
  /* 永冻深渊:六臂雪花,骨白晶心 */
  icon_set_frost: [
    "........kk........",
    ".......kCCk.......",
    "...kk..kCCk..kk...",
    "..kCCk.kCCk.kCCk..",
    "...kCCkkCCkkCCk...",
    "....kCCCCCCCCk....",
    ".....kCCwwCCk.....",
    "..kkkkCCwwCCkkkk..",
    ".kCCCCCCwwCCCCCCk.",
    ".kCCCCCCwwCCCCCCk.",
    "..kkkkCCwwCCkkkk..",
    ".....kCCwwCCk.....",
    "....kCCCCCCCCk....",
    "...kCCkkCCkkCCk...",
    "..kCCk.kCCk.kCCk..",
    "...kk..kCCk..kk...",
    ".......kCCk.......",
    "........kk........",
  ],
  /* 熔火回响:岩山淌下赤金熔岩 */
  icon_set_magma: [
    "..................",
    "......kkkkkk......",
    ".....kYYRRYYk.....",
    "....kRYRRRRYRk....",
    "....kkRkkkkRkk....",
    "...kaaRkaakRaak...",
    "...kaaRRaaRRaak...",
    "..kaaaRRRaRRaaak..",
    "..kaaaaRRRRaaaak..",
    ".kaaaaaRRRaaaaaak.",
    ".kaaaaaaRaaaaaaak.",
    "kaaaaaaaRRaaaaaaak",
    "kaaaaaaaRRaaaaaaak",
    "kaaaaaaaaRaaaaaaak",
    "kaaaaaaaaaaaaaaaak",
    "kkkkkkkkkkkkkkkkkk",
    "..................",
    "..................",
  ],
  /* 幽冥潮汐:翠瞳紫魂 */
  icon_set_phantom: [
    "......kkkkkk......",
    "....kkPPPPPPkk....",
    "...kPPVVVVVVPPk...",
    "..kPVVVVVVVVVVPk..",
    "..kPVkkVVVVkkVPk..",
    "..kVkEEkVVkEEkVk..",
    "..kVkEEkVVkEEkVk..",
    "..kVVkkVVVVkkVVk..",
    "..kVVVVVVVVVVVVk..",
    "..kVVVVVVVVVVVVk..",
    "..kVVVVVVVVVVVVk..",
    "..kVVVVVVVVVVVVk..",
    "..kVVkVVVkkVVVkVk.",
    "..kVk.kVk..kVk.k..",
    "..kk...kk...kk....",
    "..................",
    "..................",
    "..................",
  ],
};
